services:
  postgres:
    image: postgres:14
    container_name: hms_postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s 

  hms-backend:
    build: .
    container_name: hms_nest_backend
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres_data:
